### ISSUE TITLE
SOAP-potential file not found

### ISSUE THREAD

**Issue by yauz3** [gaoqiweng/PROTAC-Model#4]
Hi. I would like to write something about error I faced : "SOAP-potential file not found". This maybe helps someone.

The codes were:
> ../bin/frodock 3hfl_fv_ASA.pdb 3hfl_ly2_ASA.pdb -w 3hfl_fv_W.ccp4 -e 3hfl_fv_E.ccp4 --th 10 -d 3hfl_fv_DS.ccp4,3hfl_ly2_DS.ccp4 -o dock.dat

The outputs:
frodock> Name H convention: pdb
frodock> Force Field: CHARMM
frodock>
frodock> Reading receptor PDB
frodock>  Receptor PDB center: -0.598341 -64.294624 -5.272957
frodock>  Receptor accessibility read from receptor PDB
frodock>   ...occupancy column seems to have ASA values
frodock>  Creating Accessibility map from receptor PDB...
frodock>  Accessibility map created from receptor PDB
frodock> Weights SOAP 0.700000 Tobi 15.000000
frodock> Reading SOAP-potential file: ../bin/soap.bin 
frodock> ��  SOAP-potential file not found
ERROR: ��

Then dock.dat file becomes empty, which breaks the code. 

You need to add one line to eliminate the error. 
1) go to utils/frodock.py
2) Add line just after frodock_gcc = '%s/bin/frodock_gcc' % FRODOCK  (line 37)
write : soap='%s/bin/soap.bin' % FRODOCK
3) Go to line frodock execution line (it was 46, but now 47)
edit that code like that:
os.system(frodock_docking + ' receptor_ASA.pdb target_ASA.pdb -w receptor_W.ccp4 -e receptor_E.ccp4 '
                        '--th 10 -d receptor_DS.ccp4,target_DS.ccp4 -t E -o dock.dat --around %s -s %s' %(site, soap))

I hope it helps someone.

**Comment by yauz3** [comment]
Hi again,
Does this error:
"Could not triangle bounds smooth molecule." affect the results?

Thank you a lot.

**Comment by zcq23** [comment]
@yauz3 Hello, does this error: "Could not triangle bounds smooth molecule." affect the results? because i met the new error: Traceback (most recent call last):
  File "/data2/zcq/protac/PROTAC-Model-master/main.py", line 102, in <module>
    main()
  File "/data2/zcq/protac/PROTAC-Model-master/main.py", line 91, in main
    fro.filter_frodock(cpu, lig_locate_num, target_smi, rec_smi)
  File "/data2/zcq/protac/PROTAC-Model-master/utils/frodock.py", line 126, in filter_frodock
    pool.map(filtering, para_list)
  File "/home/zqy/miniconda3/envs/protac6/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/zqy/miniconda3/envs/protac6/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range
after this error. 
Thanks a lot.

**Comment by Krystal0310** [comment]
Hi, have you solved it? I have the same problem:
[16:56:05] WARNING: More than one matching pattern found - picking one
[16:56:05] Could not triangle bounds smooth molecule.
/bin/bash: /root/miniconda2/lib/libtinfo.so.6: no version information available (required by /bin/bash)

**Comment by yauz3** [comment]
Hi, @Krystal0310. 

You need to find the SOAP file on the internet. Then, adopt codes, which I already defined in the previous comment.

I hope you can solve it.

**Comment by WangNa-log** [comment]
> @yauz3 Hello, I also met this error, and the previous sentence of this error is "sh: ./bin/vina: access denied. " Granting permission to the execution file (vina) can solve the problem.  The process is:  step1：access the directory of executable files for the installed vina software.  step2: import the command: chmod +x *.
